trigger:
  branches:
    include:
      - master

pool:
  vmImage: "gitversion /output json /showvariable SemVer"

# github ejecuta este build, para validar y ejecutar,
# es decir, dos veces
# esta instrucción asigna que no se ejecute en el pull request (para validar).
# sino, que solo se ejecute al modificar la rama.
pr: none


steps:
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.6.4'
      includePrerelease: false
    displayName : "Configurando gitversion"

  - task: gitversion/execute@0
    inputs:
      useConfigFile: true
      configFilePath: "deploy/gitConfig.yml" 
    displayName: "generando version actual"

  
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"
    

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: '--no-git-tag-version version $(FullSemVer)'
      customRegistry: 'useFeed'
      customFeed: '$(default-feed)'
 

  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(Build.SourcesDirectory)"
      contents: "**"
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: "Copy Build"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/npm"
      artifactName: npm
    displayName: "Publish npm artifact"
